version: "3.8"

services:
  backend-app:
    build:
      context: ./docker/backend
      dockerfile: Dockerfile.dev
    container_name: backend-app
    restart: unless-stopped
    command: wait-for database:3306 -t 120 -- /usr/local/bin/start.sh
    ports:
      - "3333:3333"
    volumes:
      - ./backend:/home/node/backend
    depends_on:
      - database
    networks:
      - network-app

  database:
    image: mysql:8.2
    container_name: database
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=tutilabsdb
      - MYSQL_ROOT_PASSWORD=mypasswordroot
      - MYSQL_PASSWORD=mypassword
    ports:
      - "3306:3306"
    volumes:
      - ./_dbData:/var/lib/mysql
    networks:
      - network-app

networks:
  network-app:
    driver: bridge